version: '3.8'

services:
  db_postgres:
    image: postgres:15-alpine 
    container_name: faculdade_tech_db
    restart: always
    environment:
      POSTGRES_USER: user_faculdade_demo
      POSTGRES_PASSWORD: sua_senha_demo_aqui
      POSTGRES_DB: faculdade_tech_demo
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432" 

  app:
    build: .
    container_name: faculdade_tech_api
    restart: always
    environment: 
      NODE_ENV: development
      PORT: 3000
      JWT_SECRET: "chave_secreta_para_apresentacao"
      DB_HOST: db_postgres 
      DB_PORT: 5432
      DB_NAME: faculdade_tech_demo
      DB_USER: user_faculdade_demo
      DB_PASSWORD: sua_senha_demo_aqui
    ports:
      - "8000:3000" 
    depends_on:
      - db_postgres
    volumes:
      - .:/app
      - /app/node_modules 
    command: npm start
    
volumes:
  postgres_data: